# -*- coding: utf-8 -*-
"""day 2 class activity

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZtZcEY4CU-_4SiSdu4UNss1zhhWDlrpb
"""

from sklearn import tree
features=[[300,0,4],[255,0,4],[150,1,5],[270,1,4],[200,0,5],[180,1,5],[170,0,4]]
labels=[0,0,1,1,0,1,1]
myClassifier=tree.DecisionTreeClassifier()
myModel=myClassifier.fit(features,labels)
myModel.predict([[175,0,4]])

from sklearn import tree
features=[[1,1,1],[0,0,0],[1,0,1],[1,0,0],[0,1,0],[0,0,0],[1,0,1]]
lables=["TFF","FFT","TFF","FTF","TFF","TFT","FFF"]
myClassifier = tree.DecisionTreeClassifier()
myModel=myClassifier.fit(features,lables)
myModel.predict([[0,1,0]])

from sklearn import tree
features=[[1,1,1],[0,0,0],[1,0,1],[1,0,0],[0,1,0],[0,0,0],[1,0,1]]
lables=["Tcc","cc","Tcc","cc","Tcc","Tcc","cc"]
myClassifier = tree.DecisionTreeClassifier()
myModel=myClassifier.fit(features,lables)
myModel.predict([[0,1,0]])

pip install gradio

import gradio as gr
from sklearn import tree

# Training data
features = [[1, 1, 1], [0, 0, 0], [1, 0, 1], [1, 0, 0], [0, 1, 0], [0, 1, 1]]
labels = ["TCC", "CC", "TCC", "TCC", "CC", "CC"]

# Training the model
myClassifier = tree.DecisionTreeClassifier()
myModel = myClassifier.fit(features, labels)

# Create Gradio interface
inputs = [
    gr.Slider(0, 1, step=1, label="Victim (0: No, 1: Yes)"),
    gr.Slider(0, 1, step=1, label="Money Involved (0: No, 1: Yes)"),
    gr.Slider(0, 1, step=1, label="Major Tools Used (0: No, 1: Yes)")
]
outputs = gr.Textbox(label="Predicted Crime Type")

interface = gr.Interface(
    fn=lambda victim, money_involved, major_tools_used: myModel.predict([[victim, money_involved, major_tools_used]])[0],
    inputs=inputs,
    outputs=outputs,
    title="Crime Type Predictor"
)

interface.launch()